INSERT INTO funcion(nombre, id_funcion) VALUES
('Incio', null),
('Tablas Básicas', null ),
('Negocio', 2),
('Categorías', 2),
('Parámetros', 2),
('Administracion', null),
('Sistema', 6),
('Seguridad funcional', 6),
('Base de datos', 6),
('Portal Web', null),
('Inicio del portal', 10),
('Galería', 10),
('Empresa', 10),
('Suscripción', 10),
('Marketing', null),
('Servicios', 15),
('Promociones', 15),
('Consejos', 15),
('Clientes', null),
('Ordenes de servicio', null),
('Solicitudes', 20),
('Citas', 20),
('Reclamos', 20),
('Atención al cliente', null),
('Reportes', null),
('Estructurados', 25),
('Estadísticas', 25);