INSERT INTO tipo_parametro (nombre, clasificacion) VALUES
('Gustos y preferencias', 'GP'),
('Datos Basicos', 'DB'),
('Ojo',  'CA'),
('Labio', 'CA'),
('Piel', 'CA'),
('Rostro','CA'),
('Cabello', 'CA');

------------------------------------------------------------
INSERT INTO categoria_parametro(id_tipo_parametro, id_categoria_servicio) VALUES
(3, 2),
(4, 2),
(5, 1),
(5, 2),
(6, 1),
(6, 2),
(7, 1),
(7, 2);

------------------------------------------------------------------------------------------------
INSERT INTO parametro(nombre, id_tipo_parametro)VALUES
('¿Prefieres llevar el cabello suelto o recogido?', 1),
('¿Estas interesado en servicios de peluqueria para bodas?', 1),
('¿Asistes con frecuencia a eventos formales?', 1),
('¿Qué tipo de actividades haces con más frecuencia?', 1),
('¿Qué tipo de servicios prefieres?', 1),
('Sexo', 2),
('Rango de edad', 2),
('Estado civil', 2),
('¿Tiene hijos?', 2),
('Nivel de estudios', 2),
('Tipo de ojo', 3),
('Color de ojo', 3),
('Tipo de labio', 4),
('Color de labio', 4),
('Tipo de piel', 5),
('Subtono de piel', 5),
('Tez', 5),
('Inperfecciones del rostro', 6),
('Tipo rostro', 6),
('Forma del cabello', 7),
('Tipo de cabello', 7),
('Longitud de cabello', 7),
('Color de cabello', 7);
--------------------------------------------------------------------------------------------------------


INSERT INTO valor_parametro (id_parametro, nombre, descripcion)VALUES
(2, 'Suelto', 'Te identificas como una persona libre, y te sientes comoda con tu cabellos'),
(2, 'Recogido', 'Eres mas conservadora, prefieres el cabello recogido'),
(3, 'Si', ' '),
(3, 'No', ' '),
(4, 'Si', ' '),
(4, 'No', ' '),
(5, 'Fiestas', 'Cualquier fiesta con unos amigos'),
(5, 'Salida con amigos', 'Salidas de día para compartir con tus amigos'),
(5, 'Ir a la universidad', 'Soy estudiante, prefiero ir con estilo natural' ),
(5, 'Ir al trabajo', 'Trabajo todos los dias, debo lucir muy formal'),
(6, 'Peluqueria', 'Es lo que me gusta con mas frecuencia'),
(6, 'Maquillaje', 'Es lo que gusta y aplico con mas frecuencia'),
(7, 'Hombre', ' '),
(7, 'Mujer', ' '),
(8, 'joven', 'de 18 a 25 años'),
(8, 'adulto joven', 'de 26 a 35 años'),
(8, 'adulto', 'de 36 a 49 años'),
(8, 'adulto mayor', 'de 50 a 80 años'),
(9, 'Soltero', ' '),
(9, 'Casado', ' '),
(9, 'Viudo', ' '),
(9, 'Divorciado', ' '),
(9, 'En concubinato', ' '),
(10, 'si', ' '),
(10, 'no', ' '),
(11, 'Bachillerato', ' '),
(11, 'Universitario', ' '),
(11, 'Postgrado', ' '),
(12, 'Ojo normal', 'Su nombre se debe a la forma parecida que tiene con las “almendras” y es el tipo más común, por lo que también se conocen como “ojos normales”'),
(12, 'Ojos juntos o estrechos','Este tipo de ojos se caracterizan porque la distancia entre ellos es más pequeño que lo estándar,  ya que suele ser menor a la extensión de un ojo.'),
(12, 'Ojos hundidos','Estos ojos se caracterizan porque el párpado tiene la tendencia de ser más prominente en el borde externo que en el interno. Presentan una sombra o “bolsa” en la esquina interior.'),
(12,  'Ojos saltones o prominentes', 'Es justo lo contrario a lo anterior, caracterizándose por un abultamiento o  elevación con respecto al interior de los ojos.'),
(12, 'Ojos asiaticos', 'Los ojos que pertenecen a este tipo son más pequeños que la media y muy fáciles de reconocer porque los pliegues de los párpados no son visibles, generándose un espacio mayor entre la ceja y los ojos'),
(12, 'Ojos caidos', 'Los ojos caídos tienen esta apariencia cuando el párpado móvil parece ejercer peso sobre el ojo estando abierto. Algunos rostros asiáticos tienen este tipo de ojos.'),
(12, 'Ojos apartados', 'Son ojos que se ven pequeños con respecto al resto de los rasgos faciales, puesto que la distancia que los separa es mayor que la extensión de un ojo'),
(13, 'Castaño', 'Los ojos de color marrón, café o castaño contienen grandes cantidades de melanina en la parte anterior del iris'),
(13, 'Ambar', 'Los ojos de color ámbar son de un tono que puede ir del amarillento al rojizo dorado y de tinte cobrizo'),
(13, 'Avellana', 'El color pardo avellana para los ojos es un tono intermedio entre el marrón y el verde'),
(13, 'Verde', 'Los ojos de color verde son el producto de moderadas cantidades de melanina. El verde es un color intermedio entre los tonos marrón y azul o gris'),
(13, 'Azul', 'Los ojos de color azul o celeste contienen bajas cantidades de melanina en la parte anterior del iris'),
(13, 'Gris', 'Aún se desconocen los factores que conllevan a que el iris adquiera el aspecto gris.'),
(14, 'Labios gruesos', 'Se suele creer que a este tipo de labios les sienta bien cualquier color, sin embargo hay que evitar a toda costa aquellas tonalidades demasiado claras, los brillos y los gloss para no caer en demasiadas exageracione'),
(14, 'Labios finos', 'Al contrario que los labios gruesos, en este tipo de maquillaje lo ideal es aplicar un gloss o un poco de brillo ya que el efecto será mucho más llamativo.'),
(14, 'Labios asimetricos', ' Cuando el ancho del labio superior o inferior no es homogéneo se dice que estamos ante unos labios asimétricos, aunque lo más habitual es que el labio superior sea más fino que el labio inferior'),
(14, 'Labios caidos', ' Entre los tipos de labios que hay, los caídos se da cuando las comisuras de los mismos van hacia abajo, por lo que se deben corregir las imperfecciones para poder lucir unos labios bonitos y perfectos.'),
(14, 'Boca grande', ' A pesar de que una boca grande pueda ser atractiva, hay trucos de maquillaje que pueden disimularla y hacer que el exceso se reduzca'),
(14, 'Boca pequea', ' Las bocas pequeñas también pueden potenciarse a través de diferentes trucos de maquillaje muy fáciles de hacer en casa. La boca pequeña no implica tener unos labios finos, también pueden ser gruesos'),

(16, 'normal', '"Normal" es un término de amplio uso para referirse a una piel en buen equilibrio. El término científico para piel con buen equilibrio es el de "eudérmica".'),
(16, 'seca', 'La piel seca puede percibirse tirante y áspera, con aspecto apagado'),
(16, 'grasa', '"Grasa" se usa para describir un tipo de piel que tiene una elevada producción de sebo. Esta producción excesiva se denomina "seborrea"'),
(16, 'mixta', 'La piel mixta es, como su nombre indica, una piel que consta de una mezcla de tipos de piel.'),
(17, 'Frio', 'Son pieles en las que predominan los reflejos rojos, rosados, azulados o violáceos. Si los accesorios de color plata lucen mejor en tí, las venas de tu muñeca son más violetas que verdes'),
(17, 'Calido', 'Son pieles con reflejos amarillos, durazno y dorados. Si te favorecen más los complementos de color oro, te bronceas con facilidad y el color predominante de las venas de tu muñeca es más el verde que el violeta, tienen un subtono de piel cálido'),
(17, 'Neutral', 'También denominado por los expertos como “oliva”, es el que poseen la mayoría de las españolas. Se caracteriza por tener una mezcla de los dos subtonos anteriores'),
(18, 'Palida', 'El tipo 1 de piel es el más claro de todos los tonos de piel. Se caracteriza por una piel extraordinariamente pareja, con pecas y de color blanco como el papel'),
(18, 'Calra', 'Los tipos 2 y 3 son claras y por lo general pálidas. El tipo de tez 2 tiende al pálido y a menudo se quema cuando se expone al sol. Es posible broncearse ligeramente con esta tez'),
(18, 'Bronceada', 'Hay dos tipos de cutis que se encuentran en las personas de Oriente Medio y del Mediterráneo, son los tipos 4 y 5 de tonos de piel.'),
(18, 'Oscura', 'El tipo 6 es la tez que contiene la mayor cantidad de melanina. Se refiere a la piel negra que nunca se quema con la exposición solar'),

(19, 'Granos y rojeces', 'El acné común es un problema que puede prolongarse más allá de la adolescencia, complicando en gran medida la cuestión del maquillaje'),
(19, 'Manchas y cicatrices', 'Puede que tu dolor de cabeza sean las manchas provocadas por el sol o las manchas oscuras que han ido apareciendo con el paso de los años alrededor de los ojos o la boca'),
(19, 'Ojeras y bolsas', 'Para disimular bolsas bajo los ojos, debemos «borrar» la línea que las marca con un corrector natural y difuminarlo con la yema de los dedos'),

(20, 'Redondo', 'Es un tipo de rostro con formas suaves, ángulos no tan definidos, pómulos y barbilla marcada y mejillas anchas'),
(20, 'Alargado', 'Un rostro alargado, necesita cortes de pelo que favorezcan los lados de la cara, es decir, que den el efecto de que hay más volumen en esta parte del rostro.'),
(20, 'Corazón', 'Este tipo de rostro se caracteriza por manejar unas mejillas fuertes y una barbilla fina muy marcada, creando la forma de un corazón'),
(20, 'Cuadrado', 'El rostro cuadrado se caracteriza por tener la frente y el mentón anchos, con una barbilla muy poco definida y contornos demasiado rectos.'),
(20, 'Ovalado', 'Es la forma más simétrica, por lo que casi todos los peinados favorecen a este tipo de rostro. Es ligeramente más ancho en las mejillas y un poco más estrecho hacia el mentón'),
(20, 'Rectangular', 'Tienen la mandíbula recta y la frente del mismo ancho, es más largo que ancho. Lo que más le favorece es acortar visualmente la cara.'),

(21, 'Rizado', 'Cabello con rizos'),
(21, 'Ondulado', 'Cabello que presenta ondas'),
(21, 'Liso', 'Cabello totalmente liso'),
(21, 'Mixto', 'Cabello que es diverso'),
(22, 'Seco', 'Este tipo de pelo tiene muy poca grasa, por lo tanto se rompe con facilidad y es mucho más frágil. '),
(22, 'Grasoso', 'En este caso, sucede todo lo contrario al seco, el exceso de grasa es el que mata la belleza de tu melena'),
(22, 'Normal', 'El tipo de cabello que todas deseamos conseguir y si tu cabello es así ¡Enhorabuena! Genera la grasa justa para evitar la sequedad y sin dar sensación de grasa.'),


(23, 'Largo', 'Se considera cabello largo a una longitud al nivel medio de la espalda de la persona a evaluar'),
(23, 'Extralargo', 'Se considera cabello extralargo a una longitud que sobre pase el nivel medio de la espalda de la persona a evaluar'),
(23, 'Medio', 'Se considera cabello medio a una longitud por debajo del hombro de la persona a evaluar'),
(23, 'Corto', 'Se considera cabello corto a una longitud al nivel de los hombros de la persona a evaluar'),
(23, 'Extracorto', 'Se considera cabello extra corto a una longitud por encima del nivel de los hombros de la persona a evaluar'),
(24, 'Negro', 'Se considera el color como uno de los colores de cabello naturales, ademas de tintes'),
(24, 'Moreno', 'color natural'),
(24, 'Castaño oscuro', 'color natural'),
(24, 'Castaño', 'color natural'),
(24, 'Castaño claro', 'color natural'),
(24, 'Rubio oscuro', 'color natural'),
(24, 'Rubio', 'color natural'),
(24,'Rubio calor', 'color natural'),
(24, 'Rubio muy claro', 'color natural'),
(24, 'Platino', 'color natural');