INSERT INTO funcion(nombre) VALUES
('Tablas Básicas' ),
('Negocio',),
('Categorias'),
('Parametros'),
('Administracion'),
('Sistema'),
('Seguridad Funciona'),
('Base de Datos'),
('Portal  Web'),
('Inicio del portal'),
('Galería'),
('Empresa'),
('Suscripcion'),
('Marketing'),
('Servicios'),
('Promociones'),
('Consejos'),
('Clientes'),
('Ordenes de servico'),
('Solicitudes'),
('Citas'),
('Reclamos'),
('Atencion al Cliente'),
('Reportes'),
('Estructurados'),
('Estadisticos');

