
INSERT INTO tipo_insumo (nombre)VALUES
('Base'),
('Corrector'),
('Polvo'),
('Sombras'),
('Pincel'),
('Esponja'),
('Iluminador'),
('Delineador'),
('Corrector'),
('Rimel'),
('Rubor'),
('Depotar'),
('Fijador'),
('Lápiz'),
('Hidratante'),
('Pigmento'),
('Prebase'),
('Fijador de cabello'),
('Acondicionador'),
('Champú'),
('Tinte de cabello'),
('Tijera'),
('Peine'),
('Pinza'),
('Plancha de cabello'),
('Secador'),
('Brocha quita pelos'),
('Paletina');